Repository canalplus/rx-player, pull requests merged in 2018-12, with the labels that each got.

#399 api: translate most IETF language tags into generic ISO639-3 codes
  src/utils/languages/index.ts
Labels: bug, in-review, languages

#400 Fix/do not refresh static manifests
  src/parsers/manifest/dash/indexes/timeline.ts
  src/parsers/manifest/dash/node_parsers/index.ts
  src/parsers/manifest/smooth/index.ts
  src/parsers/manifest/smooth/representationIndex.ts
Labels: DASH, Smooth, bug, in-review

#408 compat/smooth: patch ISOBMFF even on Edge (Rollback)
  src/compat/index.ts
Labels: Compatibility, Smooth

#409 Misc/npm package updates
  package-lock.json
  package.json
  src/compat/eme/MediaKeys.ts
  src/utils/bytes.ts
  src/utils/strings.ts
Labels: Code, typescript

#393 Fixed requestMediaKeySystemAccess in mediaCapabiltiiesProber and compat.
  src/compat/eme/MediaKeys.ts
  src/experimental/tools/mediaCapabilitiesProber/probers/DRMInfos/index.ts
  tests/integration/experimental/mediaCapabilitiesProber/getCompatibleDRM.js
  tests/integration/index.js
Labels: Compatibility, in-review, tools

#398 xLinks onLoad support
  demo/full/scripts/contents.js
  src/core/pipelines/create_parser.ts
  src/core/pipelines/manifest/index.ts
  src/core/pipelines/segment/segment_fetcher.ts
  src/net/dash/index.ts
  src/net/smooth/index.ts
  src/net/types.ts
  src/parsers/manifest/dash/index.ts
  src/parsers/manifest/dash/node_parsers/Period.ts
  src/parsers/manifest/dash/parseMPD.ts
  src/parsers/manifest/dash/parsePeriods.ts
Labels: DASH, enhancement, in-review

#418 parsers/isobmff: simplify isobmff parsers
  src/parsers/containers/isobmff/index.ts
Labels: Code, in-review

#419 Misc/manifest tolerance improvements
  src/core/init/load_on_media_source.ts
  src/manifest/adaptation.ts
  src/manifest/index.ts
  src/manifest/period.ts
  src/manifest/representation.ts
  src/parsers/manifest/dash/get_presentation_live_gap.ts
  src/parsers/manifest/dash/node_parsers/AdaptationSet.ts
  src/parsers/manifest/dash/parseAdaptationSets.ts
  src/parsers/manifest/dash/parseMPD.ts
  src/parsers/manifest/dash/parseRepresentations.ts
  src/parsers/manifest/smooth/index.ts
  src/parsers/manifest/types.ts
  tests/integration/scenarios/dash_live.js
Labels: Code, in-review

#422 Throw if no supported manifest audio or video track
  src/manifest/period.ts
Labels: DASH, Smooth, in-review

#416 Net/return manifest directly
  doc/architecture/pipelines/index.md
  src/core/api/index.ts
  src/core/buffer/period_buffer_manager.ts
  src/core/init/index.ts
  src/core/pipelines/index.ts
  src/core/pipelines/manifest/index.ts
  src/manifest/adaptation.ts
  src/manifest/index.ts
  src/manifest/period.ts
  src/transports/dash/index.ts
  src/transports/smooth/index.ts
  src/transports/types.ts
Labels: Code, in-review

#424 utils/tests: try to implement an interval-free concatMapLatest test f…
  src/utils/__tests__/concat_map_latest.test.ts
Labels: tests

#425 dash: handle `S` nodes (segments) with an @r attribute at `-1`
  src/parsers/manifest/dash/indexes/base.ts
  src/parsers/manifest/dash/indexes/helpers.ts
  src/parsers/manifest/dash/indexes/timeline.ts
  src/parsers/manifest/dash/node_parsers/S.ts
  src/parsers/manifest/dash/node_parsers/SegmentTimeline.ts
  src/parsers/manifest/dash/parseAdaptationSets.ts
  src/parsers/manifest/dash/parsePeriods.ts
  src/parsers/manifest/dash/parseRepresentations.ts
Labels: DASH, bug, in-review

#426 Manifest: better infer the minimum time of a manifest
  src/core/api/from_wallclock_time.ts
  src/manifest/index.ts
Labels: DASH, Smooth, in-review

#427 manifest: redefine Manifest to be an EventEmitter
  src/core/api/index.ts
  src/core/buffers/adaptation/adaptation_buffer.ts
  src/core/buffers/buffer_orchestrator.ts
  src/core/buffers/period/period_buffer.ts
  src/core/buffers/representation/representation_buffer.ts
  src/core/init/create_buffer_clock.ts
  src/core/init/events_generators.ts
  src/core/init/index.ts
  src/core/init/load_on_media_source.ts
  src/core/init/types.ts
  src/manifest/index.ts
  src/utils/eventemitter.ts
Labels: Code, in-review

#433 tests/ci: add apveyor.yml
  appveyor.yml
  package.json
  tests/integration/scenarios/dash_live.js
Labels: tests
