Repository canalplus/rx-player, pull requests merged in 2020-02, with the labels that each got.

#673 Use padding when fast switching on Safari
  src/compat/__tests__/should_append_buffer_after_padding.test.ts
  src/compat/should_append_buffer_after_padding.ts
  src/config.ts
  src/core/api/public_api.ts
  src/core/buffers/representation/get_needed_segments.ts
  src/core/buffers/representation/representation_buffer.ts
  tslint.json
Labels: Compatibility

#678 Detection browser without user agent
  src/compat/browser_detection.ts
Labels: Compatibility

#680 parsers/manifest: set a stricter adaptation type
  src/parsers/manifest/dash/infer_adaptation_type.ts
  src/parsers/manifest/dash/parse_adaptation_sets.ts
  src/parsers/manifest/smooth/create_parser.ts
  src/parsers/manifest/types.ts
  src/parsers/manifest/utils/check_manifest_ids.ts
Labels: code

#685 dash/smooth: fix base url resolution logic when query parameters contain "/" characters
  src/utils/__tests__/resolve_url.test.ts
  src/utils/resolve_url.ts
Labels: DASH, Smooth, bug

#686 tools/parseBIFThumbnails: do not return an ArrayBuffer of the whole thing
  src/experimental/tools/parseBIFThumbnails.ts
  src/parsers/images/bif.ts
  tests/integration/scenarios/parseBifThumbnails.js
Labels: bug, tools

#671 Filter unsupported quality levels when parsing Smooth manifest
  src/parsers/manifest/smooth/create_parser.ts
  src/parsers/manifest/smooth/get_codecs.ts
  src/transports/smooth/isobmff/create_video_init_segment.ts
  src/transports/smooth/segment_loader.ts
Labels: Compatibility, Smooth
