Repository canalplus/rx-player, pull requests merged in 2020-03, with the labels that each got.

#688 transports: avoid using double equality, even for null/undefined checks
  src/parsers/containers/isobmff/get_box.ts
  src/transports/dash/image_pipelines.ts
  src/transports/dash/init_segment_loader.ts
  src/transports/dash/low_latency_segment_loader.ts
  src/transports/dash/manifest_parser.ts
  src/transports/dash/segment_loader.ts
  src/transports/dash/text_loader.ts
  src/transports/dash/text_parser.ts
  src/transports/metaplaylist/manifest_loader.ts
  src/transports/metaplaylist/pipelines.ts
  src/transports/smooth/extract_timings_infos.ts
  src/transports/smooth/isobmff/create_audio_init_segment.ts
  src/transports/smooth/isobmff/create_video_init_segment.ts
  src/transports/smooth/isobmff/parse_tfxd.ts
  src/transports/smooth/isobmff/patch_segment.ts
  src/transports/smooth/isobmff/replace_moof.ts
  src/transports/smooth/pipelines.ts
  src/transports/smooth/segment_loader.ts
  src/transports/utils/call_custom_manifest_loader.ts
  src/transports/utils/document_manifest_loader.ts
  src/transports/utils/get_isobmff_timing_infos.ts
  src/transports/utils/parse_text_track.ts
Labels: code

#675 maximumTime-LocalTransport-parsers
  src/parsers/manifest/local/parse_local_manifest.ts
Labels: Local Manifest

#690 MPD@minimumUpdatePeriod set to 0: solution 2 - config
  src/config.ts
  src/parsers/manifest/dash/parse_mpd.ts
Labels: DASH

#700 code: Manifest structure improvements
  src/core/init/get_initial_time.ts
  src/core/init/manifest_update_scheduler.ts
  src/manifest/__tests__/manifest.test.ts
  src/manifest/manifest.ts
  src/parsers/manifest/dash/parse_mpd.ts
  src/parsers/manifest/local/parse_local_manifest.ts
  src/parsers/manifest/metaplaylist/metaplaylist_parser.ts
  src/parsers/manifest/smooth/create_parser.ts
  src/parsers/manifest/types.ts
  src/utils/__tests__/id_generator.test.ts
  src/utils/id_generator.ts
Labels: code

#699 doc: generalize the use of JSDoc for type, variable and functions doc
  src/core/api/clock.ts
  src/core/api/get_player_state.ts
  src/core/api/media_element_track_choice_manager.ts
  src/core/api/option_parsers.ts
  src/core/api/public_api.ts
  src/core/api/track_choice_manager.ts
  src/core/init/get_initial_time.ts
  src/core/init/manifest_update_scheduler.ts
  src/core/pipelines/manifest/create_manifest_pipeline.ts
  src/manifest/__tests__/manifest.test.ts
  src/manifest/adaptation.ts
  src/manifest/are_same_content.ts
  src/manifest/manifest.ts
  src/manifest/period.ts
  src/manifest/representation.ts
  src/manifest/representation_index/static.ts
  src/manifest/representation_index/types.ts
  src/manifest/types.ts
  src/parsers/manifest/types.ts
  src/transports/types.ts
Labels: code
