Repository canalplus/rx-player, pull requests merged in 2020-09, with the labels that each got.

#792 smooth: skip discontinuity even when we're in the middle of it
  src/parsers/manifest/smooth/representation_index.ts
Labels: Ready for Review, Smooth, buffer

#771 buffers: simplify code readability for the `filterGarbageCollectedSegments` and fix end check issue
  src/core/buffers/representation/get_needed_segments.ts
Labels: Ready for Review, buffer, bug

#776 manifest: do not update manifest uris on partial updates
  src/manifest/manifest.ts
Labels: Ready for Review, bug

#753 Global EME unit tests
  doc/architecture/files.md
  jest.config.js
  src/compat/eme/custom_media_keys/old_webkit_media_keys.ts
  src/compat/eme/custom_media_keys/types.ts
  src/compat/eme/custom_media_keys/webkit_media_keys.ts
  src/compat/eme/index.ts
  src/compat/event_listeners.ts
  src/compat/index.ts
  src/core/eme/__tests__/__global__/get_license.test.ts
  src/core/eme/__tests__/__global__/init_data.test.ts
  src/core/eme/__tests__/__global__/media_key_system_access.test.ts
  src/core/eme/__tests__/__global__/media_keys.test.ts
  src/core/eme/__tests__/__global__/server_certificate.test.ts
  src/core/eme/__tests__/__global__/utils.ts
  src/core/eme/find_key_system.ts
  src/core/eme/get_media_keys.ts
  src/core/eme/session_events_listener.ts
  src/core/eme/set_server_certificate.ts
  src/core/eme/types.ts
  src/core/eme/utils/loaded_sessions_store.ts
Labels: EME, tests, work-in-progress

#769 fetchers: add the concept of "high priority" segment requests
  src/config.ts
  src/core/buffers/representation/representation_buffer.ts
  src/core/fetchers/index.ts
  src/core/fetchers/segment/__tests__/prioritizer.test.ts
  src/core/fetchers/segment/index.ts
  src/core/fetchers/segment/prioritized_segment_fetcher.ts
  src/core/fetchers/segment/prioritizer.ts
  src/core/fetchers/segment/segment_fetcher.ts
  src/core/fetchers/segment/segment_fetcher_creator.ts
Labels: Ready for Review, buffer, enhancement

#777 buffers: rename variables and functions to make get_needed_segments.ts more readable
  src/core/buffers/representation/get_needed_segments.ts
Labels: Ready for Review, code

#781 buffers: urgent quality switch now do not interrupt segment pushing operations
  src/config.ts
  src/core/buffers/adaptation/adaptation_buffer.ts
  src/core/buffers/representation/index.ts
  src/core/buffers/representation/representation_buffer.ts
Labels: Ready for Review, buffer

#788 Filter out CENC pssh with a version not set to "1"
  src/compat/eme/generate_key_request.ts
  src/parsers/containers/isobmff/get_box.ts
  src/parsers/containers/isobmff/index.ts
  tests/contents/DASH_static_broken_cenc_in_MPD/index.js
  tests/contents/DASH_static_broken_cenc_in_MPD/infos.js
  tests/contents/DASH_static_broken_cenc_in_MPD/media/audio.mp4
  tests/contents/DASH_static_broken_cenc_in_MPD/media/broken_cenc.mpd
  tests/contents/DASH_static_broken_cenc_in_MPD/media/video.mp4
  tests/contents/DASH_static_broken_cenc_in_MPD/urls.js
  tests/contents/urls.js
  tests/integration/scenarios/dash_static.js
Labels: EME, Ready for Review

#782 buffers: Rely directly on the QueuedSourceBuffer for pending operations
  src/core/buffers/representation/get_needed_segments.ts
  src/core/buffers/representation/representation_buffer.ts
  src/core/source_buffers/index.ts
  src/core/source_buffers/queued_source_buffer.ts
Labels: Ready for Review, code

#795 misc: improve logging situation in clock and SegmentInventory
  src/core/api/clock.ts
  src/core/source_buffers/segment_inventory.ts
Labels: Ready for Review

#796 abr: limit oscillation in ABR estimates
  src/config.ts
  src/core/abr/network_analyzer.ts
  src/core/abr/pending_requests_store.ts
  src/core/abr/representation_estimator.ts
Labels: ABR, Ready for Review

#793 stream: rename the "Buffer" part of the code as "Stream"
  doc/architecture/buffers/index.md
  doc/architecture/fetchers/index.md
  doc/architecture/files.md
  doc/architecture/index.md
  doc/architecture/source-buffers/segment_inventory.md
  doc/architecture/stream/index.md
  doc/architecture/stream/representation_stream.md
  doc/architecture/stream/stream_orchestrator.md
  doc/terms.md
  src/config.ts
  src/core/abr/abr_manager.ts
  src/core/abr/index.ts
  src/core/abr/representation_estimator.ts
  src/core/api/public_api.ts
  src/core/api/track_choice_manager.ts
  src/core/fetchers/segment/segment_fetcher_creator.ts
  src/core/init/create_media_source.ts
  src/core/init/create_stream_clock.ts
  src/core/init/events_generators.ts
  src/core/init/load_on_media_source.ts
  src/core/init/manifest_update_scheduler.ts
  src/core/init/types.ts
  src/core/source_buffers/garbage_collector.ts
  src/core/source_buffers/source_buffers_store.ts
  src/core/stream/adaptation/adaptation_stream.ts
  src/core/stream/adaptation/index.ts
  src/core/stream/events_generators.ts
  src/core/stream/index.ts
  src/core/stream/orchestrator/active_period_emitter.ts
  src/core/stream/orchestrator/are_streams_complete.ts
  src/core/stream/orchestrator/get_blacklisted_ranges.ts
  src/core/stream/orchestrator/index.ts
  src/core/stream/orchestrator/stream_orchestrator.ts
  src/core/stream/period/create_empty_adaptation_stream.ts
  src/core/stream/period/get_adaptation_switch_strategy.ts
  src/core/stream/period/index.ts
  src/core/stream/period/period_stream.ts
  src/core/stream/representation/append_segment_to_source_buffer.ts
  src/core/stream/representation/force_garbage_collection.ts
  src/core/stream/representation/get_buffer_padding.ts
  src/core/stream/representation/get_needed_segments.ts
  src/core/stream/representation/get_segment_priority.ts
  src/core/stream/representation/get_wanted_range.ts
  src/core/stream/representation/index.ts
  src/core/stream/representation/push_init_segment.ts
  src/core/stream/representation/push_media_segment.ts
  src/core/stream/representation/representation_stream.ts
  src/core/stream/types.ts
  src/manifest/representation_index/types.ts
Labels: Ready for Review, code, proposal

#768 DASH: MPD SegmentTemplate inheritance
  src/parsers/manifest/dash/indexes/base.ts
  src/parsers/manifest/dash/indexes/list.ts
  src/parsers/manifest/dash/indexes/template.ts
  src/parsers/manifest/dash/indexes/timeline/timeline_representation_index.ts
  src/parsers/manifest/dash/node_parsers/AdaptationSet.ts
  src/parsers/manifest/dash/node_parsers/Period.ts
  src/parsers/manifest/dash/node_parsers/Representation.ts
  src/parsers/manifest/dash/node_parsers/SegmentBase.ts
  src/parsers/manifest/dash/node_parsers/SegmentTemplate.ts
  src/parsers/manifest/dash/parse_adaptation_sets.ts
  src/parsers/manifest/dash/parse_mpd.ts
  src/parsers/manifest/dash/parse_periods.ts
  src/parsers/manifest/dash/parse_representation_index.ts
  src/parsers/manifest/dash/parse_representations.ts
  tests/contents/DASH_static_SegmentTimeline/index.js
  tests/contents/DASH_static_SegmentTimeline/media/segment_template_inheritance_as_rep.mpd
  tests/contents/DASH_static_SegmentTimeline/media/segment_template_inheritance_period_as.mpd
  tests/contents/DASH_static_SegmentTimeline/segment_template_inheritance_as_rep.js
  tests/contents/DASH_static_SegmentTimeline/segment_template_inheritance_period_as.js
  tests/contents/DASH_static_SegmentTimeline/urls.js
  tests/integration/scenarios/dash_static.js
Labels: DASH, Ready for Review

#790 Convert GUID Playready KID when necessary
  src/compat/browser_detection.ts
  src/compat/eme/get_uuid_kid_from_keystatus_kid.ts
  src/core/eme/check_key_statuses.ts
  src/core/eme/eme_manager.ts
  src/core/eme/session_events_listener.ts
  src/parsers/containers/isobmff/drm/playready.ts
  src/utils/__tests__/string_parsing.test.ts
  src/utils/string_parsing.ts
Labels: Compatibility, EME, Ready for Review

#783 Faster safer quality switch
  src/core/stream/adaptation/adaptation_stream.ts
  src/core/stream/adaptation/create_representation_estimator.ts
  src/core/stream/events_generators.ts
  src/core/stream/representation/get_needed_segments.ts
  src/core/stream/representation/representation_stream.ts
  src/core/stream/types.ts
Labels: Ready for Review, buffer

#798 Still retry all other segment's URLs when a non-retryable error happen on the request for one of them
  src/core/fetchers/utils/try_urls_with_backoff.ts
Labels: Ready for Review, bug

#797 manifest: when doing partial updates avoid removing too much Periods when one is too old
  src/manifest/manifest.ts
  src/manifest/update_periods.ts
Labels: DASH, Ready for Review, bug

#744 Dispose old media keys if different than new ones
  src/core/eme/__tests__/__global__/get_license.test.ts
  src/core/eme/__tests__/__global__/init_data.test.ts
  src/core/eme/__tests__/__global__/media_keys.test.ts
  src/core/eme/__tests__/__global__/server_certificate.test.ts
  src/core/eme/__tests__/init_media_keys.test.ts
  src/core/eme/attach_media_keys.ts
  src/core/eme/init_media_keys.ts
  src/core/eme/types.ts
  src/core/init/__tests__/is_eme_ready.test.ts
  src/core/init/create_eme_manager.ts
  src/core/init/initialize_directfile.ts
  src/core/init/initialize_media_source.ts
  src/core/init/is_eme_ready.ts
Labels: Compatibility, EME, bug

#802 Fix wrong usage of strToUtf8 when what was really wanted was Base64 decoding
  src/compat/eme/custom_media_keys/old_webkit_media_keys.ts
  src/parsers/containers/isobmff/drm/playready.ts
  src/parsers/manifest/smooth/parse_protection_node.ts
Labels: Ready for Review, bug

#803 misc: Minor code updates after sonarcloud checks
  demo/full/scripts/components/BufferContentGraph.jsx
  demo/full/scripts/controllers/Player.jsx
  demo/full/scripts/modules/player/events.js
  src/core/api/track_choice_manager.ts
  src/core/eme/types.ts
  src/core/stream/period/create_empty_adaptation_stream.ts
  src/experimental/tools/createMetaplaylist/get_duration_from_manifest.ts
  src/manifest/adaptation.ts
  src/parsers/images/bif.ts
  src/parsers/manifest/dash/indexes/__tests__/tokens.test.ts
  src/parsers/manifest/dash/indexes/get_segments_from_timeline.ts
  src/parsers/manifest/dash/indexes/template.ts
  src/parsers/manifest/dash/indexes/tokens.ts
  tests/integration/scenarios/dash_live_utc_timings.js
  tests/integration/scenarios/dash_static.js
Labels: code

#804 Release/v3.21.1
  CHANGELOG.md
  VERSION
  demo/full/scripts/contents.js
  dist/rx-player.js
  dist/rx-player.min.js
  dist/rx-player.min.js.LICENSE.txt
  doc/generated/list.html
  doc/generated/pages/api/deprecated.html
  doc/generated/pages/api/exported_types.html
  doc/generated/pages/api/index.html
  doc/generated/pages/api/local_manifest.html
  doc/generated/pages/api/player_events.html
  doc/generated/pages/api/plugins.html
  doc/generated/pages/architecture/buffers/index.html
  doc/generated/pages/architecture/fetchers/index.html
  doc/generated/pages/architecture/files.html
  doc/generated/pages/architecture/index.html
  doc/generated/pages/architecture/source-buffers/index.html
  doc/generated/pages/architecture/source-buffers/segment_inventory.html
  doc/generated/pages/architecture/stream/index.html
  doc/generated/pages/architecture/stream/representation_stream.html
  doc/generated/pages/architecture/stream/stream_orchestrator.html
  doc/generated/pages/terms.html
  doc/generated/pages/tutorials/contents_with_DRM.html
  doc/generated/pages/tutorials/quick_start.html
  doc/generated/pages/tutorials/stream_events.html
  doc/generated/pages/tutorials/track_selection.html
  doc/generated/pages/v2_to_v3.html
  package-lock.json
  package.json
  sonar-project.properties
  src/core/api/public_api.ts
Labels: release, release-ready

#808 [Proposal] remove husky dependency
  CONTRIBUTING.md
  package-lock.json
  package.json
  scripts/git-hooks/pre-commit
  scripts/git-hooks/pre-push
Labels: Ready for Review, proposal

#810 tools: Make the TextTrackRenderer not experimental anymore
  doc/api/TextTrackRenderer.md
  doc/api/index.md
  scripts/generate_builds
  src/experimental/tools/index.ts
  src/tools/TextTrackRenderer/index.ts
  src/tools/TextTrackRenderer/text_track_renderer.ts
  src/tools/index.ts
Labels: API, Ready for Review, tools
