Repository canalplus/rx-player, pull requests merged in 2021-06, with the labels that each got.

#959 Trigger the end of stream only when the last period of the content is known
  src/core/stream/orchestrator/stream_orchestrator.ts
  src/manifest/manifest.ts
  src/parsers/manifest/dash/parse_mpd.ts
  src/parsers/manifest/local/parse_local_manifest.ts
  src/parsers/manifest/metaplaylist/metaplaylist_parser.ts
  src/parsers/manifest/smooth/create_parser.ts
  src/parsers/manifest/types.ts
Labels: bug

#943 [audioTrackSwitchingMode] Perform a small seek to flush buffer instead of a reload
  src/config.ts
  src/core/init/initialize_media_source.ts
  src/core/init/types.ts
  src/core/stream/events_generators.ts
  src/core/stream/period/get_adaptation_switch_strategy.ts
  src/core/stream/period/period_stream.ts
  src/core/stream/types.ts
Labels: enhancement, languages

#941 Seek right before content end when trying to seek after it
  src/config.ts
  src/core/api/public_api.ts
  src/parsers/manifest/dash/parse_mpd.ts
Labels: API, bug

#952 Wait before setting the MediaSource duration if it is closed
  src/compat/event_listeners.ts
  src/core/init/duration_updater.ts
Labels: bug, init

#940 [Proposal] Add trick mode
  doc/api/index.md
  doc/api/manifest.md
  doc/api/player_events.md
  src/core/api/public_api.ts
  src/core/api/track_choice_manager.ts
  src/core/init/initialize_directfile.ts
  src/core/init/load_on_media_source.ts
  src/core/init/update_playback_rate.ts
  src/manifest/adaptation.ts
  src/parsers/manifest/dash/parse_adaptation_sets.ts
  src/parsers/manifest/types.ts
Labels: API, DASH, enhancement

#950 [Proposal] segment parsers now return their result synchronously
  CONTRIBUTING.md
  src/core/api/public_api.ts
  src/core/fetchers/segment/create_segment_loader.ts
  src/core/fetchers/segment/prioritized_segment_fetcher.ts
  src/core/fetchers/segment/segment_fetcher.ts
  src/core/fetchers/segment/segment_fetcher_creator.ts
  src/core/init/initialize_media_source.ts
  src/core/init/load_on_media_source.ts
  src/core/stream/adaptation/adaptation_stream.ts
  src/core/stream/orchestrator/stream_orchestrator.ts
  src/core/stream/period/period_stream.ts
  src/core/stream/representation/representation_stream.ts
  src/experimental/tools/VideoThumbnailLoader/get_initialized_source_buffer.ts
  src/experimental/tools/VideoThumbnailLoader/push_data.ts
  src/experimental/tools/VideoThumbnailLoader/types.ts
  src/transports/README.md
  src/transports/dash/add_segment_integrity_checks_to_loader.ts
  src/transports/dash/image_pipelines.ts
  src/transports/dash/segment_parser.ts
  src/transports/dash/text_parser.ts
  src/transports/local/segment_parser.ts
  src/transports/local/text_parser.ts
  src/transports/metaplaylist/pipelines.ts
  src/transports/smooth/pipelines.ts
  src/transports/types.ts
  src/utils/assert.ts
Labels: Refacto, proposal

#962 [Proposal] remove RxJS code from the transports code
  src/core/api/option_utils.ts
  src/core/fetchers/manifest/get_manifest_backoff_options.ts
  src/core/fetchers/manifest/manifest_fetcher.ts
  src/core/fetchers/segment/create_segment_loader.ts
  src/core/fetchers/segment/get_segment_backoff_options.ts
  src/core/fetchers/segment/prioritized_segment_fetcher.ts
  src/core/fetchers/segment/segment_fetcher.ts
  src/core/fetchers/segment/segment_fetcher_creator.ts
  src/core/fetchers/utils/create_request_scheduler.ts
  src/core/fetchers/utils/try_urls_with_backoff.ts
  src/core/stream/representation/representation_stream.ts
  src/experimental/tools/VideoThumbnailLoader/create_request.ts
  src/experimental/tools/VideoThumbnailLoader/get_initialized_source_buffer.ts
  src/experimental/tools/VideoThumbnailLoader/load_segments.ts
  src/experimental/tools/VideoThumbnailLoader/push_data.ts
  src/experimental/tools/VideoThumbnailLoader/thumbnail_loader.ts
  src/experimental/tools/createMetaplaylist/get_duration_from_manifest.ts
  src/transports/dash/add_segment_integrity_checks_to_loader.ts
  src/transports/dash/image_pipelines.ts
  src/transports/dash/init_segment_loader.ts
  src/transports/dash/low_latency_segment_loader.ts
  src/transports/dash/manifest_parser.ts
  src/transports/dash/pipelines.ts
  src/transports/dash/segment_loader.ts
  src/transports/dash/segment_parser.ts
  src/transports/dash/text_loader.ts
  src/transports/dash/text_parser.ts
  src/transports/local/pipelines.ts
  src/transports/local/segment_loader.ts
  src/transports/local/segment_parser.ts
  src/transports/local/text_parser.ts
  src/transports/metaplaylist/manifest_loader.ts
  src/transports/metaplaylist/pipelines.ts
  src/transports/smooth/pipelines.ts
  src/transports/smooth/segment_loader.ts
  src/transports/smooth/utils.ts
  src/transports/types.ts
  src/transports/utils/call_custom_manifest_loader.ts
  src/transports/utils/generate_manifest_loader.ts
  src/transports/utils/return_parsed_manifest.ts
  src/utils/cancellable_sleep.ts
  src/utils/id_generator.ts
  src/utils/request/fetch.ts
  src/utils/request/index.ts
  src/utils/request/xhr.ts
  src/utils/rx-from_cancellable_promise.ts
  src/utils/task_canceller.ts
  tests/integration/scenarios/initial_playback.js
  tests/integration/scenarios/manifest_error.js
  tests/integration/utils/launch_tests_for_content.js
Labels: Refacto, proposal
