Repository canalplus/rx-player, pull requests merged in 2022-06, with the labels that each got.

#1118 DASH: initial S elements without a `t` attribute implicitely begin at `0`
  src/parsers/manifest/dash/common/indexes/timeline/construct_timeline_from_elements.ts
  src/parsers/manifest/dash/common/indexes/timeline/construct_timeline_from_previous_timeline.ts
  src/parsers/manifest/dash/common/indexes/timeline/convert_element_to_index_segment.ts
  src/parsers/manifest/dash/common/indexes/timeline/timeline_representation_index.ts
Labels: bug, DASH, Priority: 1 (High)

#1122 Fix issues that could arise when handling segments starting at a negative position
  src/parsers/manifest/dash/common/indexes/get_segments_from_timeline.ts
  src/transports/utils/get_isobmff_timing_infos.ts
Labels: bug, Priority: 1 (High)

#1121 DASH: set a minimum for the first available position of an index
  src/core/stream/orchestrator/active_period_emitter.ts
  src/parsers/manifest/dash/common/indexes/base.ts
  src/parsers/manifest/dash/common/indexes/timeline/timeline_representation_index.ts
Labels: bug, DASH, Performance checks, Priority: 1 (High)

#1114 [Proposal] The demo page now uses the Minimal RxPlayer (and optionally the WASM MPD parser)
  demo/full/mpd-parser.wasm
  demo/full/scripts/controllers/Main.jsx
  demo/full/scripts/modules/player/index.js
  package.json
  scripts/fast_demo_build.js
  scripts/generate_full_demo.js
  scripts/start_demo_web_server.js
Labels: Demo, proposal, WASM

#1125 fix/ Changed how we calculate memory estimate
  src/core/stream/representation/get_needed_segments.ts
Labels: bug, Performance checks, Priority: 0 (Very high)

#1126 [Proposal] Define all API-exposed types directly in src/public_types.ts
  doc/api/Typescript_Types.md
  src/core/api/get_player_state.ts
  src/core/api/index.ts
  src/core/api/media_element_track_choice_manager.ts
  src/core/api/option_utils.ts
  src/core/api/public_api.ts
  src/core/api/track_choice_manager.ts
  src/core/decrypt/__tests__/__global__/get_license.test.ts
  src/core/decrypt/attach_media_keys.ts
  src/core/decrypt/content_decryptor.ts
  src/core/decrypt/find_key_system.ts
  src/core/decrypt/get_media_keys.ts
  src/core/decrypt/init_media_keys.ts
  src/core/decrypt/session_events_listener.ts
  src/core/decrypt/set_server_certificate.ts
  src/core/decrypt/types.ts
  src/core/decrypt/utils/media_keys_infos_store.ts
  src/core/decrypt/utils/persistent_sessions_store.ts
  src/core/fetchers/manifest/manifest_fetcher.ts
  src/core/fetchers/segment/segment_fetcher.ts
  src/core/fetchers/utils/error_selector.ts
  src/core/init/events_generators.ts
  src/core/init/initialize_directfile.ts
  src/core/init/initialize_media_source.ts
  src/core/init/link_drm_and_content.ts
  src/core/init/stream_events_emitter/index.ts
  src/core/init/stream_events_emitter/types.ts
  src/core/init/types.ts
  src/core/stream/events_generators.ts
  src/core/stream/period/get_adaptation_switch_strategy.ts
  src/core/stream/period/index.ts
  src/core/stream/period/period_stream.ts
  src/core/stream/representation/downloading_queue.ts
  src/core/stream/types.ts
  src/errors/format_error.ts
  src/errors/index.ts
  src/errors/is_known_error.ts
  src/manifest/__tests__/adaptation.test.ts
  src/manifest/adaptation.ts
  src/manifest/index.ts
  src/manifest/manifest.ts
  src/manifest/period.ts
  src/manifest/representation.ts
  src/manifest/representation_index/types.ts
  src/manifest/types.ts
  src/parsers/manifest/dash/common/indexes/timeline/timeline_representation_index.ts
  src/parsers/manifest/dash/common/parse_representations.ts
  src/parsers/manifest/metaplaylist/representation_index.ts
  src/parsers/manifest/smooth/representation_index.ts
  src/parsers/manifest/types.ts
  src/public_types.ts
  src/transports/dash/segment_loader.ts
  src/transports/local/pipelines.ts
  src/transports/metaplaylist/manifest_loader.ts
  src/transports/smooth/segment_loader.ts
  src/transports/types.ts
  src/transports/utils/call_custom_manifest_loader.ts
  src/transports/utils/generate_manifest_loader.ts
  src/utils/rx-retry_with_backoff.ts
Labels: code, proposal, Priority: 2 (Medium)

#1133 Fix fallback for license missing kid in an extended `singleLicensePer` setting
  src/core/decrypt/content_decryptor.ts
Labels: bug, DRM, Priority: 0 (Very high)

#1131 TTML: Better handle EBU-TT files by considering "tt:" namespace
  src/parsers/texttracks/ttml/get_attribute_in_elements.ts
  src/parsers/texttracks/ttml/get_parent_elements_by_tag_name.ts
  src/parsers/texttracks/ttml/html/create_element.ts
  src/parsers/texttracks/ttml/native/parse_cue.ts
  src/parsers/texttracks/ttml/nodes.ts
  src/parsers/texttracks/ttml/parse_ttml.ts
  src/parsers/texttracks/ttml/xml_utils.ts
Labels: bug, TTML

#1132 Prevent subtle race conditions linked to `paused` attribute when reloading the content
  src/compat/event_listeners.ts
  src/core/adaptive/adaptive_representation_selector.ts
  src/core/adaptive/network_analyzer.ts
  src/core/api/__tests__/get_player_state.test.ts
  src/core/api/get_player_state.ts
  src/core/api/playback_observer.ts
  src/core/api/public_api.ts
  src/core/init/content_time_boundaries_observer.ts
  src/core/init/create_stream_playback_observer.ts
  src/core/stream/adaptation/adaptation_stream.ts
  src/core/stream/adaptation/index.ts
  src/core/stream/orchestrator/stream_orchestrator.ts
  src/core/stream/period/create_empty_adaptation_stream.ts
  src/core/stream/period/period_stream.ts
  src/core/stream/reload_after_switch.ts
  src/core/stream/representation/append_segment_to_buffer.ts
  src/core/stream/representation/index.ts
  src/core/stream/representation/push_init_segment.ts
  src/core/stream/representation/push_media_segment.ts
  src/core/stream/representation/representation_stream.ts
  src/utils/rx-next-tick.ts
Labels: bug, Performance checks
