Repository canalplus/rx-player, pull requests merged in 2023-05, with the labels that each got.

#1250 On the PlayStation 5, set Infinity MediaSource duration for live contents
  src/compat/browser_detection.ts
  src/compat/has_issues_with_high_media_source_duration.ts
  src/core/init/media_source_content_initializer.ts
  src/core/init/utils/media_source_duration_updater.ts
Labels: bug, Compatibility

#1245 Demo Header: Add GitHubButton component to replace script in head
  demo/full/index.html
  demo/full/scripts/components/GitHubButton.tsx
  demo/full/scripts/controllers/Main.tsx
  demo/full/styles/style.css
  package-lock.json
  package.json
Labels: Demo

#1237 ABR: Try reducing the frequency of potential quality switches
  src/core/adaptive/__tests__/buffer_based_chooser.test.ts
  src/core/adaptive/adaptive_representation_selector.ts
  src/core/adaptive/buffer_based_chooser.ts
  src/core/adaptive/guess_based_chooser.ts
  src/core/adaptive/network_analyzer.ts
  src/core/adaptive/utils/representation_score_calculator.ts
  src/default_config.ts
  src/utils/is_null_or_undefined.ts
Labels: ABR, proposal
