Repository canalplus/rx-player, pull requests merged in 2024-02, with the labels that each got.

#1370 Don't re-load a Manifest's optional external resource each time if initial failed
  src/manifest/classes/manifest.ts
Labels: bug, Priority: 1 (High), needs-backporting

#1374 Make `attachWorker` return a promise
  src/core/api/public_api.ts
  src/core/init/multithread/main_thread/multi_thread_content_initializer.ts
  src/core/init/multithread/worker/worker_portal.ts
  src/errors/worker_initialization_error.ts
  src/multithread_types.ts
Labels: Priority: 0 (Very high), MultiThread

#1373 Auto-install Rust compiler toolchain locally for CI and JS devs of other projects
  .github/workflows/checks.yml
  .gitignore
  package.json
  scripts/build_wasm_release.sh
  scripts/install_rust_toolchain.sh
Labels: Priority: 0 (Very high)

#1372 WASM: Temporarily rollback on wasm-opt dependency for release builds to make it work on some LG + Samsung TVs
  package-lock.json
  package.json
  scripts/wasm-optimize.mjs
  src/parsers/manifest/dash/wasm-parser/README.md
Labels: Compatibility, WASM, Priority: 0 (Very high), Priority: 1 (High)

#1375 Release/v4.0.0 rc.2
  CHANGELOG.md
  VERSION
  package-lock.json
  package.json
  sonar-project.properties
  src/core/api/public_api.ts
Labels: release

#1380 Fix `representationListUpdate` event
  src/core/api/public_api.ts
Labels: bug, Priority: 0 (Very high)

#1381 fix(demo): text for limit video resolution updates when selecting another options
  demo/full/scripts/components/Options/VideoAdaptiveSettings.tsx
Labels: Demo
