Repository canalplus/rx-player, pull requests merged in 2024-11, with the labels that each got.

#1591 DRM: Only check cached MediaKeySystemAccess compatibility with most w…
  src/main_thread/decrypt/find_key_system.ts
Labels: DRM

#1592 [Proposal] Make SharedReference's clearSignal param mandatory
  src/core/main/worker/worker_main.ts
  src/main_thread/init/multi_thread_content_initializer.ts
  src/playback_observer/media_element_playback_observer.ts
  src/playback_observer/types.ts
  src/playback_observer/utils/generate_read_only_observer.ts
  src/playback_observer/worker_playback_observer.ts
  src/utils/reference.ts
Labels: proposal

#1599 fix: getVideoTrack() should not returned unplayable representations
  src/main_thread/api/public_api.ts
Labels: bug, API, Priority: 0 (Very high)
