Repository canalplus/rx-player, pull requests merged in 2024-09, with the labels that each got.

#1527 fix: correctly remove period from active periods if time get out of period range in mutli-thread
  src/core/main/worker/worker_main.ts
Labels: bug, Priority: 0 (Very high), MultiThread

#1467 Move Stream's DownloadingQueue into fetchers' SegmentQueue
  src/core/fetchers/README.md
  src/core/fetchers/index.ts
  src/core/fetchers/segment/index.ts
  src/core/fetchers/segment/segment_queue.ts
  src/core/fetchers/segment/segment_queue_creator.ts
  src/core/fetchers/segment/task_prioritizer.ts
  src/core/main/worker/content_preparer.ts
  src/core/main/worker/worker_main.ts
  src/core/stream/adaptation/adaptation_stream.ts
  src/core/stream/adaptation/types.ts
  src/core/stream/orchestrator/stream_orchestrator.ts
  src/core/stream/period/period_stream.ts
  src/core/stream/period/types.ts
  src/core/stream/representation/representation_stream.ts
  src/core/stream/representation/types.ts
  src/core/types.ts
  src/main_thread/init/media_source_content_initializer.ts
  src/multithread_types.ts
Labels: proposal, Priority: 2 (Medium), CMCD

#1532 Fix logging string in a Worker environment sent back to main thread
  src/utils/logger.ts
Labels: bug

#1530 Add A1 KSTB 40XX to our list of devices which cannot reuse MediaKeys
  src/compat/__tests__/can_reuse_media_keys.test.ts
  src/compat/browser_detection.ts
  src/compat/can_reuse_media_keys.ts
Labels: bug, Compatibility, Priority: 1 (High)

#1521 ci: add workflow to publish a package with gzip
  .github/workflows/publish_test_package.yml
  .npmignore
Labels: Priority: 1 (High)

#1538 [v3] Add A1 KSTB 40XX to our list of devices which cannot reuse MediaKeys
  src/compat/__tests__/can_reuse_media_keys.test.ts
  src/compat/browser_detection.ts
  src/compat/can_reuse_media_keys.ts
Labels: DRM, Compatibility, Priority: 1 (High), legacy-v3

#1536 [v3] Treat codecs beginning with `hev1` as hevc
  src/utils/are_codecs_compatible.ts
Labels: Compatibility, Priority: 1 (High), legacy-v3

#1534 [v3] Fix bug where active Period might never be known
  src/core/segment_buffers/segment_buffers_store.ts
Labels: bug, Priority: 1 (High), legacy-v3

#1541 fix(WASM parser): parse correctly <Label> to a tag and not an attribute
  src/parsers/manifest/dash/wasm-parser/rs/events.rs
  src/parsers/manifest/dash/wasm-parser/rs/processor/mod.rs
  src/parsers/manifest/dash/wasm-parser/ts/generators/AdaptationSet.ts
  src/parsers/manifest/dash/wasm-parser/ts/generators/Label.ts
  src/parsers/manifest/dash/wasm-parser/ts/types.ts
Labels: bug, DASH, WASM, Priority: 1 (High)

#1543 fix(WASM parser): parse correctly <Label> to a tag and not an attribute
  src/parsers/manifest/dash/wasm-parser/rs/events.rs
  src/parsers/manifest/dash/wasm-parser/rs/processor/mod.rs
  src/parsers/manifest/dash/wasm-parser/ts/generators/AdaptationSet.ts
  src/parsers/manifest/dash/wasm-parser/ts/generators/Label.ts
  src/parsers/manifest/dash/wasm-parser/ts/types.ts
Labels: bug, DASH, WASM

#1510 [Proposal] Re-export config in v4 and synchronize main thread config and worker config
  package.json
  src/config.ts
  src/core/main/worker/worker_main.ts
  src/default_config.ts
  src/main_thread/api/public_api.ts
  src/multithread_types.ts
Labels: proposal, Priority: 2 (Medium)

#1546 Fix some issues that may arise on BUFFER_FULL situations
  src/core/stream/adaptation/adaptation_stream.ts
  src/core/stream/representation/utils/append_segment_to_buffer.ts
Labels: bug, Priority: 0 (Very high)

#1535 [v3] fix(safari): video not starting because key are never considered…
  src/compat/eme/custom_media_keys/types.ts
  src/compat/eme/eme-api-implementation.ts
  src/compat/eme/get_init_data.ts
  src/compat/event_listeners.ts
  src/core/decrypt/content_decryptor.ts
  src/core/decrypt/types.ts
Labels: bug, DRM, Compatibility, Priority: 1 (High), legacy-v3

#1544 [v3] Work-around firefox 129 windows bug
  src/core/decrypt/__tests__/__global__/media_key_system_access.test.ts
  src/core/decrypt/__tests__/__global__/utils.ts
  src/core/decrypt/attach_media_keys.ts
  src/core/decrypt/content_decryptor.ts
  src/core/decrypt/find_key_system.ts
  src/core/decrypt/get_media_keys.ts
  src/core/decrypt/utils/media_keys_infos_store.ts
Labels: bug, DRM, Compatibility

#1553 [Proposal] Add noCheck scripts and use it in our publish_test_package CI script
  .github/workflows/publish_test_package.yml
  package.json
  scripts/generate_build.mjs
Labels: proposal

#1556 Fix MULTI_THREAD timing issue on Samsung TV
  src/core/main/worker/worker_main.ts
  src/main_thread/init/multi_thread_content_initializer.ts
Labels: bug, Priority: 0 (Very high), MultiThread

#1548 fix(safari): initial seek time not taken into account with fromLastPosition
  src/main_thread/init/directfile_content_initializer.ts
  src/main_thread/init/utils/initial_seek_and_play.ts
Labels: bug, Compatibility, Priority: 0 (Very high)
