Repository canalplus/rx-player, pull requests merged in 2024-08, with the labels that each got.

#1483 DASH: Be more optimistic on the buffer depth of DASH contents
  src/parsers/manifest/dash/common/__tests__/manifest_bounds_calculator.test.ts
  src/parsers/manifest/dash/common/indexes/template.ts
  src/parsers/manifest/dash/common/indexes/timeline/timeline_representation_index.ts
  src/parsers/manifest/dash/common/manifest_bounds_calculator.ts
  src/parsers/manifest/dash/common/parse_mpd.ts
  tests/integration/scenarios/dash_live.test.js
  tests/integration/scenarios/dash_live_multi_periods.test.js
  tests/integration/scenarios/dash_live_utc_timings.test.js
Labels: bug, DASH, Priority: 1 (High)

#1484 Detect codecs supported by the CDM to choose appropriate representation (2)
  src/core/main/worker/worker_main.ts
  src/default_config.ts
  src/experimental/features/__tests__/local.test.ts
  src/experimental/features/__tests__/metaplaylist.test.ts
  src/experimental/features/local.ts
  src/experimental/features/metaplaylist.ts
  src/experimental/tools/mediaCapabilitiesProber/__tests__/probers/defaultCodecFinder.test.ts
  src/experimental/tools/mediaCapabilitiesProber/probers/defaultCodecsFinder.ts
  src/features/features_object.ts
  src/features/list/__tests__/dash.test.ts
  src/features/list/__tests__/smooth.test.ts
  src/features/list/dash.ts
  src/features/list/dash_wasm.ts
  src/features/list/smooth.ts
  src/features/types.ts
  src/main_thread/api/public_api.ts
  src/main_thread/decrypt/__tests__/__global__/utils.ts
  src/main_thread/decrypt/content_decryptor.ts
  src/main_thread/decrypt/find_key_system.ts
  src/main_thread/decrypt/get_media_keys.ts
  src/main_thread/decrypt/utils/__tests__/is_compatible_codec_supported.test.ts
  src/main_thread/decrypt/utils/is_compatible_codec_supported.ts
  src/main_thread/init/directfile_content_initializer.ts
  src/main_thread/init/media_source_content_initializer.ts
  src/main_thread/init/multi_thread_content_initializer.ts
  src/main_thread/init/types.ts
  src/main_thread/init/utils/initialize_content_decryption.ts
  src/main_thread/init/utils/update_manifest_codec_support.ts
  src/main_thread/tracks_store/track_dispatcher.ts
  src/main_thread/tracks_store/tracks_store.ts
  src/manifest/classes/__tests__/adaptation.test.ts
  src/manifest/classes/__tests__/manifest.test.ts
  src/manifest/classes/__tests__/period.test.ts
  src/manifest/classes/__tests__/representation.test.ts
  src/manifest/classes/adaptation.ts
  src/manifest/classes/codec_support_cache.ts
  src/manifest/classes/index.ts
  src/manifest/classes/manifest.ts
  src/manifest/classes/period.ts
  src/manifest/classes/representation.ts
  src/manifest/index.ts
  src/manifest/types.ts
  src/manifest/utils.ts
  src/minimal.ts
  src/mse/index.ts
  src/mse/main_codec_support_prober.ts
  src/mse/types.ts
  src/mse/worker_codec_support_prober.ts
  src/multithread_types.ts
  src/utils/are_codecs_compatible.ts
  tests/integration/utils/launch_tests_for_content.js
Labels: DRM, Priority: 0 (Very high)

#1491 Dependency updates
  .eslintrc.js
  CHANGELOG.md
  demo/tsconfig.json
  package-lock.json
  package.json
  src/compat/browser_compatibility_types.ts
  src/core/segment_sinks/inventory/segment_inventory.ts
  src/main_thread/api/public_api.ts
  src/main_thread/init/media_source_content_initializer.ts
  src/manifest/classes/__tests__/update_period_in_place.test.ts
  src/mse/main_media_source_interface.ts
  src/mse/types.ts
  src/parsers/manifest/utils/__tests__/update_segment_timeline.test.ts
  src/parsers/texttracks/ttml/html/__tests__/__global__/html_ttml_parser.test.ts
  src/public_types.ts
  src/tools/TextTrackRenderer/text_track_renderer.ts
  src/utils/__tests__/array_find.test.ts
  src/utils/__tests__/array_find_index.test.ts
  src/utils/request/xhr.ts
  src/utils/weak_map_memory.ts
  tsconfig.json
Labels: Priority: 3 (Low)

#1479 fix(safari): video not starting because key are never considered usable for a track
  src/compat/eme/custom_media_keys/types.ts
  src/compat/eme/eme-api-implementation.ts
  src/compat/eme/get_init_data.ts
  src/compat/event_listeners.ts
  src/main_thread/decrypt/content_decryptor.ts
  src/main_thread/decrypt/types.ts
Labels: bug, DRM, DirectFile, Compatibility, Priority: 0 (Very high)

#1492 [v3] DASH: Be more optimistic on the buffer depth of DASH contents
  src/parsers/manifest/dash/common/__tests__/manifest_bounds_calculator.test.ts
  src/parsers/manifest/dash/common/indexes/template.ts
  src/parsers/manifest/dash/common/indexes/timeline/timeline_representation_index.ts
  src/parsers/manifest/dash/common/manifest_bounds_calculator.ts
  src/parsers/manifest/dash/common/parse_mpd.ts
  tests/integration/scenarios/dash_live.js
  tests/integration/scenarios/dash_live_SegmentTemplate.js
  tests/integration/scenarios/dash_live_utc_timings.js
Labels: DASH, legacy-v3

#1495 Work-around firefox 129 windows bug
  src/main_thread/decrypt/__tests__/__global__/media_key_system_access.test.ts
  src/main_thread/decrypt/__tests__/__global__/utils.ts
  src/main_thread/decrypt/attach_media_keys.ts
  src/main_thread/decrypt/content_decryptor.ts
  src/main_thread/decrypt/find_key_system.ts
  src/main_thread/decrypt/get_media_keys.ts
  src/main_thread/decrypt/utils/media_keys_infos_store.ts
Labels: bug, Priority: 0 (Very high)

#1500 [v3] Fix auto-play on tizen when it starts on a discontinuity
  src/core/init/utils/initial_seek_and_play.ts
Labels: bug, Priority: 0 (Very high), legacy-v3

#1499 Treat codecs beginning with `hev1` as hevc
  src/utils/are_codecs_compatible.ts
Labels: bug, Priority: 0 (Very high)

#1501 [Proposal] Add `filterPlayableRepresentations` property to audio and video tracks API
  doc/api/Track_Selection/getAudioTrack.md
  doc/api/Track_Selection/getAvailableAudioTracks.md
  doc/api/Track_Selection/getAvailableVideoTracks.md
  doc/api/Track_Selection/getVideoTrack.md
  src/main_thread/api/public_api.ts
  src/main_thread/tracks_store/tracks_store.ts
Labels: API, proposal, Priority: 2 (Medium)
