Repository canalplus/rx-player, pull requests merged in 2025-03, with the labels that each got.

#1523 [Proposal] Improve `FREEZING` mechanisms and add `Representation` avoidance mechanism
  src/core/main/common/DecipherabilityFreezeDetector.ts
  src/core/main/common/FreezeResolver.ts
  src/core/main/common/synchronize_sinks_on_observation.ts
  src/core/main/worker/content_preparer.ts
  src/core/main/worker/worker_main.ts
  src/core/stream/adaptation/adaptation_stream.ts
  src/core/stream/orchestrator/stream_orchestrator.ts
  src/default_config.ts
  src/main_thread/api/__tests__/option_utils.test.ts
  src/main_thread/api/option_utils.ts
  src/main_thread/api/public_api.ts
  src/main_thread/init/media_source_content_initializer.ts
  src/main_thread/init/multi_thread_content_initializer.ts
  src/main_thread/init/utils/create_core_playback_observer.ts
  src/main_thread/init/utils/rebuffering_controller.ts
  src/manifest/classes/index.ts
  src/manifest/classes/manifest.ts
  src/manifest/classes/representation.ts
  src/manifest/index.ts
  src/multithread_types.ts
  src/playback_observer/media_element_playback_observer.ts
  src/playback_observer/types.ts
  src/playback_observer/worker_playback_observer.ts
  src/public_types.ts
Labels: proposal, Priority: 1 (High)

#1625 [Proposal] set LogFormat to `full` on RxPlayer's debug mode
  src/index.ts
  src/minimal.ts
Labels: Priority: 3 (Low)

#1657 fix: check that ec-3 codec is supported when encrypted
  src/default_config.ts
  src/experimental/tools/mediaCapabilitiesProber/__tests__/probers/defaultCodecFinder.test.ts
  src/experimental/tools/mediaCapabilitiesProber/probers/defaultCodecsFinder.ts
  src/main_thread/decrypt/__tests__/__global__/utils.ts
  src/main_thread/decrypt/__tests__/find_key_system.test.ts
  src/main_thread/init/utils/__tests__/update_manifest_codec_support.test.ts
  src/utils/__tests__/are_codecs_compatible.test.ts
  src/utils/are_codecs_compatible.ts
Labels: Priority: 1 (High)

#1662 Misc/vitest3 fix
  .github/workflows/checks.yml
  package-lock.json
  package.json
  tests/globalSetup.mjs
  tests/memory/index.test.js
  tsconfig.dev.commonjs.json
  tsconfig.dev.json
  vitest.config.mjs
Labels: tests, dependencies

#1659 [Proposal] Make Performance test report HTML and to be collapsed by default
  .github/workflows/perfs.yml
  tests/performance/run.mjs
Labels: tests, proposal, Perf

#1670 DRM: Fix `KEY_UPDATE_ERROR` by not translating it into a `KEY_LOAD_ERROR`
  src/main_thread/decrypt/session_events_listener.ts
Labels: bug, DRM
