Repository canalplus/rx-player, pull requests merged in 2025-07, with the labels that each got.

#1708 fix: some subtitle missed on multiple period assets
  src/main_thread/text_displayer/html/html_text_displayer.ts
Labels: Priority: 0 (Very high)

#1710 Try to fix event skipping test which fails a third of a time
  tests/integration/scenarios/dash_stream-events.test.js
Labels: work-in-progress

#1713 Fix persistent session loading when content has no key id
  src/main_thread/decrypt/utils/persistent_sessions_store.ts
Labels: bug, DRM, Priority: 1 (High)

#1716 Allow application to reset an audio/video track when fallbacking from all the others' one
  src/main_thread/api/public_api.ts
  src/main_thread/tracks_store/tracks_store.ts
  tests/integration/scenarios/drm_base.js
Labels: work-in-progress, Priority: 1 (High)

#1715 feat: add disableAudioTrack API
  demo/scripts/controllers/knobs/AudioTrack.tsx
  demo/scripts/modules/player/index.ts
  doc/Getting_Started/Tutorials/Selecting_a_Track.md
  doc/api/Player_Events.md
  doc/api/Track_Selection/disableAudioTrack.md
  doc/api/Track_Selection/disableVideoTrack.md
  doc/reference/API_Reference.md
  src/main_thread/api/public_api.ts
  src/main_thread/tracks_store/media_element_tracks_store.ts
  src/main_thread/tracks_store/tracks_store.ts
  tests/integration/scenarios/audio_video_not_supported.test.js
  tests/integration/scenarios/dash_multi-track.test.js
  tests/integration/scenarios/drm_base.js
Labels: Priority: 2 (Medium)

#1720 Fix: representation returned by public API has incorrect shape
  src/main_thread/api/__tests__/public_api.test.ts
  src/main_thread/api/public_api.ts
  src/manifest/utils.ts
Labels: bug, Priority: 1 (High)

#1718 Thumbnails: Cache pending thumbnail request
  demo/scripts/components/ThumbnailPreview.tsx
  src/core/fetchers/index.ts
  src/core/fetchers/thumbnails/index.ts
  src/core/fetchers/thumbnails/thumbnail_fetcher.ts
  src/core/main/common/get_thumbnail_data.ts
  src/main_thread/init/media_source_content_initializer.ts
  src/main_thread/render_thumbnail.ts
Labels: thumbnails
