Repository canalplus/rx-player, pull requests merged in 2025-04, with the labels that each got.

#1691 fix(firefox): check extensibly Playready DRMs support before using them
  src/compat/can_rely_on_request_media_key_system_access.ts
Labels: bug

#1694 fix(DRM): renew the mediaKeySystemAccess on Edge and Firefox when using a Playready keySystem.
  src/compat/__tests__/should_renew_media_key_system_access.test.ts
  src/compat/should_renew_media_key_system_access.ts
  src/main_thread/decrypt/find_key_system.ts
Labels: DRM, Priority: 0 (Very high)

#1690 Add information on key system to an `EncryptedMediaError`
  doc/api/Player_Errors.md
  src/errors/__tests__/encrypted_media_error.test.ts
  src/errors/__tests__/is_known_error.test.ts
  src/errors/encrypted_media_error.ts
  src/main_thread/decrypt/content_decryptor.ts
  src/main_thread/decrypt/find_key_system.ts
  src/main_thread/decrypt/get_media_keys.ts
  src/main_thread/decrypt/session_events_listener.ts
  src/main_thread/decrypt/set_server_certificate.ts
  src/main_thread/decrypt/utils/check_key_statuses.ts
  src/main_thread/decrypt/utils/media_keys_attacher.ts
  src/main_thread/init/multi_thread_content_initializer.ts
  src/main_thread/init/utils/initialize_content_decryption.ts
Labels: DRM, Priority: 2 (Medium)

#1696 fix: prevent unnecessary resources usage by inactive worker
  src/main_thread/api/public_api.ts
Labels: MultiThread
